[package]
name = "cemplox"
version = "2.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
rayon = "1.10"
anyhow = "1.0.97"
env_logger = "0.11.8"
log = "0.4.27"
num_cpus = "1.16.0"
crossbeam-channel = "0.5.13"
memmap2 = "0.9.5"
